### ISSUE TITLE
Colors are messed up | Windows

### ISSUE THREAD

**Issue by ProHackTech** [s0md3v/Hash-Buster#18]
Colors do not show on Windows command prompt and powershell. Tested on Windows 10 and 8. Screenshot below:

![Screenshot](https://user-images.githubusercontent.com/47453894/58445015-6cc6f380-812d-11e9-8a40-2f87cf8fb756.PNG)

**Comment by Nike-Prallow** [comment]
At this time Hash-Buster isn‘t supported for windows.

**Comment by ProHackTech** [comment]
thanks. issue closed.
