### ISSUE TITLE
Cannot Used

### ISSUE THREAD

**Issue by jeraldpunx** [s0md3v/Hash-Buster#21]
![image](https://user-images.githubusercontent.com/5249781/62628556-1c0a1d00-b95e-11e9-81ff-876e5f0efafd.png)

**Comment by s0md3v** [comment]
install `requests`

**Comment by jeraldpunx** [comment]
I have this result on
`python hash.py -s d6c6f395e3348e3948d95937c9d2caab021b04b0433473df42ff89098c1eaaa5110d5bab5e6d07a19af5551e06534bad4896d60e93c9f9c32c41c6d2a0ded024`

![image](https://user-images.githubusercontent.com/5249781/62666515-51425980-b9b6-11e9-84f9-6c24fc46382d.png)

**Comment by s0md3v** [comment]
Thanks, I fixed it.
