### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Bluely-NO-STALKING-MYSELF-ALLOWED** [s0md3v/Hash-Buster#31]
...

**Comment by 1UC1F3R616** [comment]
- Site `https://www.nitrxgen.net/` is down. Need to find some other site for cracking hashes
- If you know any such site then tell.

**Comment by 1UC1F3R616** [comment]
@BluelyTASer use [this](https://hashes.com/en/decrypt/hash) site but it cann't be used in script because of captcha
